<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-04-27 14:58

$extensionPath = t3lib_extMgm::extPath('pazpar2');
$extensionClassesPath = t3lib_extMgm::extPath('pazpar2') . 'Classes/';
return array(
	'tx_pazpar2_controller_pazpar2controller' => $extensionClassesPath . 'Controller/Pazpar2Controller.php',
	'tx_pazpar2_domain_model_query' => $extensionClassesPath . 'Domain/Model/Query.php',
	'tx_pazpar2_viewhelpers_resultviewhelper' => $extensionClassesPath . 'ViewHelpers/ResultViewHelper.php',
);
?>