<?php
return array(
	'BE' => array(
		'disable_exec_function' => '0',
		'installToolPassword' => '7c68019aff42ab5929c42aea9a441bcd',
		'lockIP' => '0',
		'loginSecurityLevel' => 'rsa',
		'versionNumberInFilename' => '0',
	),
	'DB' => array(
		'database' => 't3_vlib1',
		'extTablesDefinitionScript' => 'extTables.php',
		'host' => '127.0.0.1',
		'password' => '',
		'username' => 'root',
	),
	'EXT' => array(
		'extConf' => array(
			'ajaxgroupsearch' => 'a:1:{s:7:"enable.";a:11:{s:5:"page.";a:4:{s:11:"storage_pid";s:1:"1";s:8:"shortcut";s:1:"1";s:16:"content_from_pid";s:1:"1";s:9:"mount_pid";s:1:"1";}s:9:"fe_users.";a:1:{s:9:"usergroup";s:1:"0";}s:9:"be_users.";a:1:{s:14:"db_mountpoints";s:1:"0";}s:10:"be_groups.";a:2:{s:14:"db_mountpoints";s:1:"1";s:21:"tx_templavoila_access";s:1:"1";}s:11:"tt_content.";a:2:{s:5:"pages";s:1:"1";s:7:"records";s:1:"1";}s:13:"sys_template.";a:2:{s:9:"nextLevel";s:1:"1";s:7:"basedOn";s:1:"1";}s:10:"sys_dmail.";a:2:{s:4:"page";s:1:"1";s:10:"use_domain";s:1:"1";}s:16:"sys_dmail_group.";a:3:{s:5:"pages";s:1:"1";s:11:"static_list";s:1:"1";s:11:"mail_groups";s:1:"1";}s:8:"tt_news.";a:2:{s:7:"related";s:1:"1";s:4:"page";s:1:"1";}s:12:"tt_products.";a:2:{s:11:"related_uid";s:1:"1";s:8:"note_uid";s:1:"1";}s:21:"tt_products_articles.";a:1:{s:11:"uid_product";s:1:"1";}}}',
			'beko_debugster' => 'a:3:{s:7:"ip_mask";s:0:"";s:10:"steps_back";s:1:"3";s:12:"useDevIpMask";s:1:"1";}',
			'cag_linkchecker' => 'a:1:{s:15:"setPageTSconfig";s:1:"1";}',
			'devlog' => 'a:11:{s:10:"maxLogRuns";s:2:"15";s:14:"entriesPerPage";s:2:"25";s:7:"maxRows";s:4:"1000";s:8:"optimize";s:1:"0";s:8:"dumpSize";s:7:"1000000";s:11:"minLogLevel";s:1:"0";s:11:"excludeKeys";s:0:"";s:14:"highlightStyle";s:60:"padding: 2px; background-color: #fc3; border: 1px solid #666";s:16:"refreshFrequency";s:1:"2";s:13:"prototypePath";s:0:"";s:11:"autoCleanup";s:1:"0";}',
			'em' => 'a:1:{s:17:"selectedLanguages";s:2:"de";}',
			'extbase' => 'a:0:{}',
			'fed' => 'a:8:{s:29:"enableBackendRecordController";s:1:"0";s:26:"enableFluidContentElements";s:1:"0";s:24:"enableFluidPageTemplates";s:1:"0";s:18:"enableSolrFeatures";s:1:"0";s:21:"enableFrontendPlugins";s:1:"0";s:30:"enableIntegratedBackendLayouts";s:1:"0";s:28:"increaseExtbaseCacheLifetime";s:1:"1";s:31:"enableFallbackFluidPageTemplate";s:1:"0";}',
			'lang' => 'a:0:{}',
			'nkwgok' => 'a:2:{s:11:"opacBaseURL";s:40:"https://opac.sub.uni-goettingen.de/DB=1/";s:7:"CSSPath";s:0:"";}',
			'piwik' => 'a:1:{s:20:"showFaultyConfigHelp";s:1:"1";}',
			'realurl' => 'a:5:{s:10:"configFile";s:0:"";s:14:"enableAutoConf";s:1:"0";s:14:"autoConfFormat";s:1:"0";s:12:"enableDevLog";s:1:"1";s:19:"enableChashUrlDebug";s:1:"0";}',
			'saltedpasswords' => 'a:2:{s:3:"FE.";a:2:{s:7:"enabled";s:1:"1";s:21:"saltedPWHashingMethod";s:28:"tx_saltedpasswords_salts_md5";}s:3:"BE.";a:5:{s:7:"enabled";s:1:"1";s:21:"saltedPWHashingMethod";s:28:"tx_saltedpasswords_salts_md5";s:11:"forceSalted";s:1:"0";s:15:"onlyAuthService";s:1:"0";s:12:"updatePasswd";s:1:"1";}}',
			'sevenpack' => 'a:0:{}',
			'simulatestatic' => 'a:0:{}',
			't3jquery' => 'a:13:{s:15:"alwaysIntegrate";s:1:"1";s:18:"dontIntegrateOnUID";s:0:"";s:9:"configDir";s:19:"uploads/tx_t3jquery";s:13:"jQueryVersion";s:5:"1.7.x";s:15:"jQueryUiVersion";s:0:"";s:18:"jQueryTOOLSVersion";s:0:"";s:17:"integrateToFooter";s:1:"0";s:23:"dontIntegrateInRootline";s:0:"";s:13:"jqLibFilename";s:23:"jquery-###VERSION###.js";s:16:"integrateFromCDN";s:1:"0";s:11:"locationCDN";s:6:"google";s:17:"enableStyleStatic";s:1:"0";s:22:"jQueryBootstrapVersion";s:0:"";}',
		),
		'extListArray' => array(
			0 => 'extbase',
			1 => 'css_styled_content',
			2 => 'version',
			3 => 'tsconfig_help',
			4 => 'context_help',
			5 => 'extra_page_cm_options',
			6 => 'impexp',
			7 => 'sys_note',
			8 => 'tstemplate',
			9 => 'tstemplate_ceditor',
			10 => 'tstemplate_info',
			11 => 'tstemplate_objbrowser',
			12 => 'tstemplate_analyzer',
			13 => 'func_wizards',
			14 => 'wizard_crpages',
			15 => 'wizard_sortpages',
			16 => 'lowlevel',
			17 => 'install',
			18 => 'belog',
			19 => 'beuser',
			20 => 'aboutmodules',
			21 => 'setup',
			22 => 'taskcenter',
			23 => 'info_pagetsconfig',
			24 => 'viewpage',
			25 => 'rtehtmlarea',
			26 => 't3skin',
			27 => 'reports',
			28 => 'realurl',
			29 => 'static_info_tables',
			30 => 'cshmanual',
			31 => 'recycler',
			32 => 'fluid',
			33 => 'beko_debugster',
			34 => 'scheduler',
			35 => 't3editor',
			36 => 'devlog',
			37 => 'ezbrequest',
			38 => 'filelist',
			39 => 'info',
			40 => 'perm',
			41 => 'rlmp_language_detection',
			42 => 'piwik',
			43 => 'func',
			44 => 'about',
			45 => 'feedit',
			46 => 'opendocs',
			47 => 'workspaces',
			48 => 'rsaauth',
			49 => 'saltedpasswords',
			50 => 'linkvalidator',
			51 => 'extdeveval',
			52 => 't3jquery',
			53 => 'pazpar2',
			55 => 'xmlinclude',
			56 => 'nkwgok',
		),
		'extList_FE' => 'extbase,css_styled_content,version,install,rtehtmlarea,t3skin,realurl,static_info_tables,fluid,beko_debugster,devlog,ezbrequest,rlmp_language_detection,piwik,feedit,workspaces,rsaauth,saltedpasswords,extdeveval,t3jquery,pazpar2,nkwgok,xmlinclude',
	),
	'EXTCONF' => array(
		'lang' => array(
			'availableLanguages' => array(
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'de',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
			),
		),
	),
	'FE' => array(
		'addRootLineFields' => ',tx_realurl_pathsegment',
		'logfile_dir' => '/var/log/typo3/',
		'pageNotFound_handling' => '404/',
	),
	'GFX' => array(
		'gdlib_png' => '1',
		'im' => '0',
		'im_combine_filename' => '',
		'im_path' => '',
		'im_path_lzw' => '',
	),
	'INSTALL' => array(
		'wizardDone' => array(
			'TYPO3\CMS\Install\CoreUpdates\InstallSysExtsUpdate' => '["info","perm","func","filelist","about","cshmanual","feedit","opendocs","recycler","t3editor","reports","scheduler","simulatestatic"]',
			'TYPO3\CMS\Install\Updates\FilemountUpdateWizard' => 1,
			'TYPO3\CMS\Install\Updates\TceformsUpdateWizard' => 'tt_content:image,pages:media,pages_language_overlay:media',
			'tx_coreupdates_installsysexts' => '1',
		),
	),
	'SYS' => array(
		'UTF8filesystem' => '1',
		'compat_version' => '6.0',
		'devIPmask' => '*',
		'displayErrors' => 2,
		'enable_DLOG' => '1',
		'encryptionKey' => 'eff43017a2a82314f23139d9daf0e129a20af589316ec80bd0084f268b67125e5a14a2b2a9e0527657b4059ebd41f44e',
		'setDBinit' => 'SET NAMES utf8;',
		'sitename' => 'Lib AAC',
	),
);
?>