<?php
return array(
	'BE' => array(
		'disable_exec_function' => '0',
		'installToolPassword' => '7c68019aff42ab5929c42aea9a441bcd',
		'loginSecurityLevel' => 'rsa',
		'showRefreshLoginPopup' => '0',
		'versionNumberInFilename' => '0',
	),
	'DB' => array(
		'database' => 't3_vlib3',
		'extTablesDefinitionScript' => 'extTables.php',
		'host' => '127.0.0.1',
		'password' => '',
		'username' => 'root',
	),
	'EXT' => array(
		'extConf' => array(
			'beko_debugster' => 'a:2:{s:7:"ip_mask";s:38:"134.76.*, 127.0.0.1, 10.0.*, 192.168.*";s:10:"steps_back";s:1:"3";}',
			'devlog' => 'a:11:{s:10:"maxLogRuns";s:2:"15";s:14:"entriesPerPage";s:2:"25";s:7:"maxRows";s:4:"1000";s:8:"optimize";s:1:"0";s:8:"dumpSize";s:7:"1000000";s:11:"minLogLevel";s:1:"0";s:11:"excludeKeys";s:0:"";s:14:"highlightStyle";s:60:"padding: 2px; background-color: #fc3; border: 1px solid #666";s:16:"refreshFrequency";s:1:"2";s:13:"prototypePath";s:0:"";s:11:"autoCleanup";s:1:"0";}',
			'em' => 'a:1:{s:17:"selectedLanguages";s:2:"de";}',
			'lang' => 'a:0:{}',
			'nkwgok' => 'a:2:{s:11:"opacBaseURL";s:39:"http://opac.sub.uni-goettingen.de/DB=1/";s:7:"CSSPath";s:0:"";}',
			'piwik' => 'a:1:{s:20:"showFaultyConfigHelp";s:1:"1";}',
			'realurl' => 'a:5:{s:10:"configFile";s:26:"typo3conf/realurl_conf.php";s:14:"enableAutoConf";s:1:"1";s:14:"autoConfFormat";s:1:"0";s:12:"enableDevLog";s:1:"0";s:19:"enableChashUrlDebug";s:1:"0";}',
			'simulatestatic' => 'a:0:{}',
			'static_info_tables' => 'a:2:{s:13:"enableManager";s:1:"0";s:5:"dummy";s:1:"0";}',
			't3jquery' => 'a:14:{s:15:"alwaysIntegrate";s:1:"1";s:17:"integrateToFooter";s:1:"0";s:17:"enableStyleStatic";s:1:"0";s:18:"dontIntegrateOnUID";s:0:"";s:23:"dontIntegrateInRootline";s:0:"";s:13:"jqLibFilename";s:23:"jquery-###VERSION###.js";s:9:"configDir";s:19:"uploads/tx_t3jquery";s:13:"jQueryVersion";s:6:"1.10.x";s:15:"jQueryUiVersion";s:6:"1.10.x";s:18:"jQueryTOOLSVersion";s:0:"";s:22:"jQueryBootstrapVersion";s:0:"";s:16:"integrateFromCDN";s:1:"0";s:11:"locationCDN";s:6:"google";s:13:"updateMessage";s:1:"0";}',
			'tt_news' => 'a:22:{s:13:"useStoragePid";s:1:"1";s:13:"noTabDividers";s:1:"0";s:25:"l10n_mode_prefixLangTitle";s:1:"1";s:22:"l10n_mode_imageExclude";s:1:"1";s:20:"hideNewLocalizations";s:1:"0";s:13:"prependAtCopy";s:1:"1";s:5:"label";s:5:"title";s:9:"label_alt";s:5:"short";s:10:"label_alt2";s:0:"";s:15:"label_alt_force";s:1:"0";s:21:"categorySelectedWidth";s:1:"0";s:17:"categoryTreeWidth";s:1:"0";s:17:"requireCategories";s:1:"1";s:11:"treeOrderBy";s:3:"uid";s:18:"categoryTreeHeigth";s:1:"5";s:18:"useInternalCaching";s:1:"1";s:11:"cachingMode";s:6:"normal";s:13:"cacheLifetime";s:1:"0";s:13:"cachingEngine";s:16:"cachingFramework";s:24:"writeCachingInfoToDevlog";s:10:"disabled|0";s:23:"writeParseTimesToDevlog";s:1:"0";s:18:"parsetimeThreshold";s:3:"0.1";}',
		),
		'extListArray' => array(
			'extbase',
			'css_styled_content',
			'version',
			'tsconfig_help',
			'context_help',
			'extra_page_cm_options',
			'impexp',
			'sys_note',
			'tstemplate',
			'tstemplate_ceditor',
			'tstemplate_info',
			'tstemplate_objbrowser',
			'tstemplate_analyzer',
			'func_wizards',
			'wizard_crpages',
			'wizard_sortpages',
			'lowlevel',
			'install',
			'belog',
			'beuser',
			'aboutmodules',
			'setup',
			'taskcenter',
			'info_pagetsconfig',
			'viewpage',
			'rtehtmlarea',
			't3skin',
			'reports',
			'realurl',
			'cshmanual',
			'recycler',
			'fluid',
			'beko_debugster',
			'scheduler',
			't3editor',
			'devlog',
			't3jquery',
			'ezbrequest',
			'filelist',
			'info',
			'perm',
			'rlmp_language_detection',
			'piwik',
			'func',
			'about',
			'feedit',
			'opendocs',
			'workspaces',
			'rsaauth',
			'saltedpasswords',
			'zamn',
			'mathematicians',
			'sys_action',
			'statictemplates',
			'tt_news',
			'nkwgok',
			'pazpar2',
			'static_info_tables',
		),
		'extList_FE' => 'extbase,css_styled_content,version,install,rtehtmlarea,t3skin,realurl,fluid,beko_debugster,devlog,t3jquery,ezbrequest,rlmp_language_detection,piwik,feedit,workspaces,rsaauth,saltedpasswords,zamn,mathematicians,statictemplates,tt_news,nkwgok,pazpar2,static_info_tables',
	),
	'EXTCONF' => array(
		'lang' => array(
			'availableLanguages' => array(
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'de',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
			),
		),
	),
	'FE' => array(
		'addRootLineFields' => ',tx_realurl_pathsegment',
		'pageNotFound_handling' => '404/',
	),
	'GFX' => array(
		'gdlib_png' => '1',
		'im' => '0',
		'im_combine_filename' => '',
		'im_path' => '',
		'im_path_lzw' => '',
	),
	'INSTALL' => array(
		'wizardDone' => array(
			'TYPO3\CMS\Install\CoreUpdates\InstallSysExtsUpdate' => '["info","perm","func","filelist","about","cshmanual","feedit","opendocs","recycler","t3editor","reports","scheduler","simulatestatic"]',
			'TYPO3\CMS\Install\Updates\TceformsUpdateWizard' => 'tt_content:image,pages:media,pages_language_overlay:media',
			'tx_coreupdates_installsysexts' => '1',
		),
	),
	'SYS' => array(
		'UTF8filesystem' => '1',
		'compat_version' => '6.1',
		'devIPmask' => '127.0.0.1,::1,134.76.162.165',
		'displayErrors' => 2,
		'encryptionKey' => 'eff43017a2a82314f23139d9daf0e129a20af589316ec80bd0084f268b67125e5a14a2b2a9e0527657b4059ebd41f44e',
		'loginCopyrightShowVersion' => '1',
		'setDBinit' => 'SET NAMES utf8;',
		'sitename' => 'vifamath',
	),
);
?>